FROM node:latest
# OLD
RUN npm install -g ganache@latest

EXPOSE 8545

WORKDIR /usr/src/app

CMD ["ganache", "--host", "0.0.0.0", "--port", "8545", "--fork", "${RPC_URL}", "--chain.networkId", "${CHAIN_ID}","--chain.chainId", "${CHAIN_ID}"]