# Generated by Django 5.2 on 2025-04-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pendingtransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='raw_transaction',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
