# Generated by Django 5.2 on 2025-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendingtransaction_analyze_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='schemas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='static_analysis_output',
            field=models.TextField(blank=True),
        ),
    ]
