# Generated by Django 5.2 on 2025-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pendingtransaction_schemas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisassembledContractFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255)),
                ('function_name', models.CharField(max_length=255)),
                ('function_code', models.TextField()),
                ('solidity_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='trace',
            field=models.TextField(blank=True),
        ),
    ]
