# Generated by Django 5.2 on 2025-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_disassembledcontractfunction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStaticAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255)),
                ('raw', models.TextField(blank=True)),
                ('bytecode_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='disassembledcontractfunction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='disassembledcontractfunction',
            name='updated_at',
        ),
    ]
